spring:
  mongodb:
    uri: ${MONGODB_URI}
  data:
    mongodb:
      auto-index-creation: true

spring.cloud.aws:
  region:
    static: ${AWS_REGION:us-east-1}
  sqs:
    endpoint: ""

logging:
  level:
    root: INFO
    br.furb: INFO
