spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/package_db?directConnection=true
      auto-index-creation: true

# ─── AWS / SQS (MiniStack) ───
spring.cloud.aws:
  region:
    static: us-east-1
  credentials:
    access-key: test
    secret-key: test
  endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4566

logging:
  level:
    root: INFO
    br.furb: DEBUG
    io.awspring.cloud: DEBUG
